### PR TITLE
Small grammatical and wording fixes

### PR DESCRIPTION
**Pull request by josephwegner**
@markoshust Awesome post!

I found a few small grammatical and wording issues, and kinda wanted to see how Airpair does this whole social authoring thing :)

### CODE REVIEW

**Comment by josephwegner** [comment]
Yikes - not sure why my Initial commit is coming in here. I would have thought it would just fork.

@airpair am I doing this right?

**Comment by jkresner** [comment]
Nope... please don't merge into master thanks!

**Comment by jkresner** [comment]
Please Create a PR from your edit branch to the parent repo edit branch! Gonna write better instructions this afternoon.

**Comment by jkresner** [comment]
It's way easier if you just make changes on the site from our editor :)

**Comment by josephwegner** [comment]
Eh - somehow I got lost in the airpair UI, and ended up getting dumped into
Github. It seemed weird, but I figured it must have been intentional.

I'll give it another go tomorrow.

**Comment by jkresner** [comment]
Yes - I have watched many before you do the same. Going to improve the UX
this afternoon thanks!

Jonathon
ᐧ

On Wed, Mar 18, 2015 at 3:46 PM, Joe Wegner notifications@github.com
wrote:

> Eh - somehow I got lost in the airpair UI, and ended up getting dumped into
> Github. It seemed weird, but I figured it must have been intentional.
> 
> I'll give it another go tomorrow.
> 
> On Wed, Mar 18, 2015, 5:44 PM Jonathon Kresner notifications@github.com
> wrote:
> 
> > It's way easier if you just make changes on the site from our editor :)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/airpair/getting-started-with-event-data-and-keenio/pull/1#issuecomment-83215736
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/getting-started-with-event-data-and-keenio/pull/1#issuecomment-83216089
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by markshust** [comment]
Hi John and Joe,

Yes I think something just went odd with how things were merged. I made a
few updates to the post, but feel free to make a new PR tomorrow and I'll
take  a look.

Mark

**Comment by josephwegner** [comment]
OK, closing this for now, I guess..

The odd thing is, when I forked from the airpair UI, it seems to have forked with the parent repo as the one owned by @airpair. @markoshust doesn't even have a repo with the name of this post, so I can't PR from github into it...

**Comment by jkresner** [comment]
The master sits on the airpair org. There is no repo on @markoshust's
account. When it gets hairy like this you can resolve it like normal code.
Merge the master edit branch into yor edit branch.

Jonathon

On Thursday, March 19, 2015, Joe Wegner notifications@github.com wrote:

> OK, closing this for now, I guess..
> 
> The odd thing is, when I forked from the airpair UI, it seems to have
> forked with the parent repo as the one owned by @airpair
> https://github.com/airpair. @markoshust https://github.com/markoshust
> doesn't even have a repo with the name of this post, so I can't PR from
> github into it...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/getting-started-with-event-data-and-keenio/pull/1#issuecomment-83605195
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Pull request closed without merging**
