### PR TITLE
small grammatical and wording updates

### PR DESCRIPTION
**Pull request by josephwegner**
alright, second try. Still an awesome post, @markoshust :)

Thanks @airpair!

### CODE REVIEW

**Comment by markshust** [comment]
Hi Joe & Airpair,

Thanks for the updates -- I wanted to merge all of these in. There is a
conflict -- what can I do to resolve this?

Thanks,
Mark

**Comment by markshust** [comment]
Hi Joe, 

If you can also leave a review on the post, that would be great so I can get this one out there! Thanks for the updates.

Mark

**Comment by josephwegner** [comment]
I'll leave a review.

Seems like this would require a rebase... but I'm not sure that is part of Airpair's social writing thing yet.

@airpair what do you suggest here? Should I just clone the repo and rebase manually? Or is there something in your UI for this?

**Comment by josephwegner** [comment]
OK, rebased. You can merge now.

**Comment by jkresner** [comment]
It's just git :)

On Thu, Mar 19, 2015 at 8:24 AM, Joe Wegner notifications@github.com
wrote:

> OK, rebased. You can merge now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/getting-started-with-event-data-and-keenio/pull/2#issuecomment-83629694
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by markshust** [comment]
I'm clearing up my GitHub account. Can someone close this PR?

**Comment by josephwegner** [comment]
Donezo. Have a good one, Mark!

**Pull request closed without merging**
